Atualização na Validação do Login
victorflll/miauche pull request #35
Opened 2021-12-11 02:03 UTC by Guylhermee

Peço que n me julgue caso esteja errado, sou burro!

2021-12-13 19:58 UTC, victorflll requested changes
Atentem-se ao nome da branch, que já foi chamada atenção mais de duas vezes. Usem SEMPRE feature/nome-da-funcionalidade.

Ademais, corrijam o que foi solicitado e testem antes de qualquer commit. Não corrigirei código que não funciona.

@Guylhermee realize as correções junto do @nxbre.

Data final: 17/12/2021.

2021-12-13 19:58 UTC, victorflll commented on lib/data/shared_preferences_helper.dart
> +    bool user = instance.getBool('USER');
Essa variável pode ser nula, como, por exemplo, na primeira vez que o aplicativo for acessado por alguém. Sendo assim, faça essa alteração.

2021-12-13 19:58 UTC, victorflll commented on lib/ui/screens/general/login_screen.dart
> +    _loadData();
Essa função deve ser carregada somente quando houver um usuário, porém isso não está acontecendo.

![image](https://user-images.githubusercontent.com/79478136/145878034-cc0e9a3b-eb5d-4c63-8e52-0ceef29e6bd8.png)

Pois o getUser está retornando sempre true, quando não deveria. Resolvam essa pendência.

Além disso, seria interessante adicionar um botão (checkbox) para que o usuário decida se quer ou não manter-se logado. Esse checkbox pode ficar à esquerda do "Esqueceu a senha". Talvez isso também resolva o retorno do usuário dado como sempre true.

- [ ] Checkbox

2021-12-13 19:58 UTC, victorflll commented on lib/ui/screens/general/login_screen.dart
> +  emailValidator(String value) {
Eu apliquei um validator geral nos campos de texto, então atualizem com o git pull antes de qualquer alteração. Além disso, esse value pode ser vazio, corrijam isso. O mesmo para o validator de senha.

2021-12-13 19:58 UTC, victorflll commented on lib/ui/screens/general/login_screen.dart
> +    bool isValid = _formKey.currentState.validate();
O currentState continua podendo ser nulo, o que resulta na necessidade da !. Não entendi o porquê da remoção, mas, adicionem de novo.

2021-12-13 19:58 UTC, victorflll commented on lib/ui/screens/general/login_screen.dart
> +          builder: (context) => HomePage(),
HomePage não existe, além de que quando usado o MaterialPageRoute para buildar a próxima página com um contexto, o dart pede o const.

2021-12-13 19:58 UTC, victorflll commented on lib/ui/screens/general/login_screen.dart
> +              builder: (context) => HomePage(),
Mais uma vez, HomePage não existe e a ausência do const. Além disso, a tela principal necessita do data, anteriormente passado por parâmetro, porém foi excluído. Tragam ele de volta.

2021-12-13 20:19 UTC, victorflll commented
Esqueci de mencionar que: adicionei vocês dois na task da SplashPage (#34), que é complemento dessa. Caso queiram, podem já implementa-la neste mesmo PR.

2021-12-14 04:52 UTC, Guylhermee commented
Por algum motivo que desconheço, consigo debugar o Miauche e mesmo executando sem erro, não consigo fazer login. Já tentei de várias formas, mas não vai. 
Por esse motivo, na única conversa q não está resolvida https://github.com/victorflll/miauche/pull/35#discussion_r768071904, realizei algumas mudanças mas não consigo testa-las. Em contrapartida consegui fazer e testar as d+. 

Além disso, tentei fazer a implementação da CheckBox e não consegui, mas segue um link útil: 
[https://ashuflutterdev.medium.com/implementing-remember-me-functionality-in-flutter-using-local-storage-45184745a5b3](url)

2021-12-14 04:58 UTC, Guylhermee commented
Pesquisei como mudar o nome da Branch, mas vi q pra fazer isso, o Git exclui a atual e cria uma nova renomeada. Para não atrapalhar as revisões que foram e serão feitas, deixei assim mesmo!

Além disso, dei commit (e com isso revisão) para que vc @victorflll ou o @nxbre, consigam testar a solução q eu implementei.

2021-12-18 03:53 UTC, merged